pipeline {
    /*Accessing build server via ssh*/
    agent {
        label 'build2'
    }
    stages {
	       
        stage('Gitlab credentials') {
            steps {
                echo 'Working on  master branch'
                    git branch: 'master', credentialsId: 'GitLab credentials', url: 'http://52.20.154.51/gitlab-instance-e8513808/leumi2'            
	    }
        }

	stage('Zip files for application') {
            steps {
                echo 'Zipping all files relevant for the Lambda application'
                echo 'Copying the zip file and the provisioning terraform file to 2nd server'
	        sh 'zip function.zip lambda_function.py license.txt readme template.yaml' 
                sh 'scp function.zip main_provision.tf ubuntu@3.83.121.222:/home/ubuntu/' 
	    }
        }
        
        stage('Create infrastructue and deploy via second server') {
            steps {
                echo 'Creating lambda and s3 infrastructure, deploying and saving in bucket via terraform'
		echo 'Entering deployment server via ssh'    
		script {
		    sshagent(['DEPLOY_KEY']) {
                        sh '''
		        ssh -o StrictHostKeyChecking=no -l ubuntu 3.83.121.222 << EOF         
                        terraform init
                        terraform apply -auto-approve
			'''
		    }
		}
            }
        }
       
        stage('create API gateway and connect to Lambda') {
            steps {
                echo 'Creating APIgateway using build server and TF and connecting it to our function'
                sh '''
                cd /home/ubuntu/gitlab/api_gateway/
                terraform init
                terraform apply -auto-approve
                '''
            }
        }
    }
    post {
        failure {
	    slackSend channel: "devops-alerts", message: "Build Failed: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
        }
	success {
            slackSend channel: "succeeded-build", message: "Build Successful: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
	}
    }
}
